
import Link from "next/link";
import {contact,whatsappLink}from"../data/contact";
import {CartButton}from"./CartDrawer";
export function Header({overlay=false}:{overlay?:boolean}){return <header className={`${overlay?"absolute left-0 right-0 top-0 bg-gradient-to-b from-[#0d0907]/90 to-transparent border-transparent":"sticky top-0 border-b border-white/10 bg-[#1d130d]/85 backdrop-blur-xl"} z-50`}><div className="max-w-7xl mx-auto px-6 py-5 flex items-center justify-between gap-6"><Link href="/"><h1 className="text-2xl font-black tracking-wide">{contact.brand}</h1><p className="text-[#d6b17a] uppercase tracking-[0.3em] text-xs mt-1">Grabados Láser Premium</p></Link><nav className="hidden lg:flex gap-6 text-sm text-stone-100"><Link href="/" className="hover:text-[#d6b17a]">Inicio</Link><Link href="/productos" className="hover:text-[#d6b17a]">Productos</Link><Link href="/#como-trabajamos" className="hover:text-[#d6b17a]">Cómo trabajamos</Link><Link href="/empresas" className="hover:text-[#d6b17a]">Empresas</Link><Link href="/nosotros" className="hover:text-[#d6b17a]">Nosotros</Link><Link href="/seguimiento" className="hover:text-[#d6b17a]">Seguimiento</Link><Link href="/contacto" className="hover:text-[#d6b17a]">Contacto</Link></nav><div className="flex gap-3"><CartButton/><a href={whatsappLink("Hola, vi tu página web y quiero consultar por un producto personalizado.")} className="hidden sm:block bg-[#b68b52] px-5 py-3 rounded-xl font-bold hover:scale-105 transition">WhatsApp</a></div></div></header>}
export function Footer(){return <footer className="border-t border-white/10 bg-[#1d130d]"><div className="max-w-7xl mx-auto px-6 py-16"><div className="grid gap-10 md:grid-cols-2 lg:grid-cols-4"><div><h3 className="text-3xl font-black">Identidad Grabada</h3><p className="mt-3 text-[#d6b17a]">Grabados láser personalizados.</p><p className="mt-5 max-w-sm text-zinc-500">Productos con identidad, diseño aprobado antes de grabar y atención directa durante todo el proceso.</p><p className="mt-5 text-sm text-zinc-600">{contact.city}</p></div><div><h4 className="font-black text-white">Tienda</h4><div className="mt-5 grid gap-3 text-zinc-400"><Link href="/productos">Productos</Link><Link href="/trabajos">Trabajos realizados</Link><Link href="/empresas">Empresas</Link><Link href="/seguimiento">Seguimiento</Link></div></div><div><h4 className="font-black text-white">Información</h4><div className="mt-5 grid gap-3 text-zinc-400"><Link href="/nosotros">Nosotros</Link><Link href="/contacto">Contacto</Link><p>Envíos a toda Argentina</p><p>Producción estimada: 2 a 5 días</p></div></div><div><h4 className="font-black text-white">Contacto</h4><div className="mt-5 grid gap-3"><a href={contact.instagramUrl} target="_blank" rel="noreferrer" className="rounded-2xl border border-white/10 px-5 py-4 text-center hover:border-[#b68b52]">Instagram</a><a href={whatsappLink("Hola, quiero consultar por un grabado personalizado.")} className="rounded-2xl bg-[#b68b52] px-5 py-4 text-center font-black">WhatsApp</a></div></div></div><div className="ig-gold-line mt-12"/><div className="mt-6 flex flex-col gap-3 text-sm text-zinc-600 md:flex-row md:items-center md:justify-between"><p>© 2026 Identidad Grabada</p><p>General Las Heras · Buenos Aires · Argentina</p></div></div></footer>}

export function WhatsAppFloat(){return <a href={whatsappLink("Hola, vi tu página web y quiero consultar por un producto personalizado.")} className="fixed bottom-6 right-6 z-30 bg-green-700 hover:bg-green-600 text-white px-5 py-4 rounded-full shadow-2xl font-black">WhatsApp</a>}
export function Title({eyebrow,title,text}:{eyebrow:string;title:string;text?:string}){return <div><p className="text-[#d6b17a] uppercase tracking-[0.3em] text-sm">{eyebrow}</p><h2 className="text-4xl md:text-6xl font-black mt-3 leading-tight">{title}</h2>{text&&<p className="text-zinc-400 text-lg mt-4 max-w-2xl leading-relaxed">{text}</p>}</div>}
export function Placeholder({title,small=false}:{title:string;small?:boolean}){return <div className="relative flex items-center justify-center w-full h-full min-h-[220px] bg-[#342217]"><div className="absolute w-52 h-52 rounded-full border-[18px] border-[#b68b52]/40"/><div className="absolute w-32 h-32 rounded-full border-[10px] border-white/20"/><div className="relative z-10 text-center px-6"><p className={`font-black text-[#d6b17a] ${small?"text-2xl":"text-4xl"}`}>Identidad Grabada</p><p className="text-zinc-500 uppercase tracking-[0.25em] text-xs mt-3">{title}</p></div></div>}
export function ImageSlot({title,small=false}:{src?:string;alt?:string;title:string;small?:boolean}){return <Placeholder title={title} small={small}/>}
export function InfoBox({title,text}:{title:string;text:string}){return <div className="bg-[#1d130d]/40 border border-white/10 rounded-2xl p-5"><p className="text-zinc-500 text-xs uppercase tracking-[0.2em] mb-2">{title}</p><p className="font-bold">{text}</p></div>}
