
import Link from"next/link";
import {notFound}from"next/navigation";
import {Header,Footer,WhatsAppFloat,InfoBox}from"../../components/ui";
import {ProductCard}from"../../components/ProductCard";
import {AddToCartButton}from"../../components/AddToCartButton";
import {ProductGallery}from"../../components/ProductGallery";
import {EngravingPreview}from"../../components/EngravingPreview";
import {getProductBySlug,getRelatedProducts,products}from"../../data/products";
export function generateStaticParams(){return products.map(product=>({slug:product.slug}))}
export function generateMetadata({params}:{params:{slug:string}}){const product=getProductBySlug(params.slug);return product?{title:`${product.name} | Identidad Grabada`,description:product.shortDescription}:{}}
export default function ProductPage({params}:{params:{slug:string}}){const product=getProductBySlug(params.slug);if(!product)notFound();const related=getRelatedProducts(product.related);return <main className="min-h-screen bg-[#050505] text-white"><Header/><section className="max-w-7xl mx-auto px-6 py-10"><div className="text-sm text-zinc-500 mb-8"><Link href="/">Inicio</Link><span className="mx-2">/</span><Link href="/productos">Productos</Link><span className="mx-2">/</span><span className="text-zinc-300">{product.name}</span></div><div className="grid lg:grid-cols-2 gap-12 items-start"><ProductGallery productName={product.name} gallery={product.gallery}/><div className="space-y-8"><div><p className="text-[#d6b17a] uppercase tracking-[0.3em] text-sm">{product.categoryLabel}</p><h1 className="text-5xl md:text-6xl font-black mt-4 leading-tight">{product.name}</h1><div className="flex gap-3 items-center mt-5"><p className="text-3xl text-[#d6b17a] font-black">{product.price}</p><span className="border border-green-700/40 text-green-300 rounded-full px-3 py-1 text-sm">{product.stock}</span></div><p className="text-zinc-400 text-lg leading-relaxed mt-6">{product.description}</p></div><div className="grid grid-cols-2 gap-4"><InfoBox title="Material" text={product.material}/><InfoBox title="Grabado" text="Láser personalizado"/><InfoBox title="Pago" text="Mercado Pago / Tarjeta"/><InfoBox title="Envío" text="Toda Argentina"/></div><EngravingPreview/><AddToCartButton slug={product.slug} name={product.name} price={product.price} priceValue={product.priceValue}/><div className="bg-[#0b0b0b] border border-white/10 rounded-[2rem] p-6"><h2 className="text-2xl font-black mb-5">Características</h2><div className="grid md:grid-cols-2 gap-3">{product.features.map(feature=><div key={feature} className="flex gap-3 text-zinc-300"><span className="text-[#d6b17a]">✓</span><span>{feature}</span></div>)}</div></div></div></div></section><section className="border-y border-white/10 bg-[#0b0b0b] py-16"><div className="max-w-7xl mx-auto px-6 grid md:grid-cols-3 gap-6"><InfoBox title="Envíos" text="A coordinar según localidad y producto."/><InfoBox title="Diseño" text="Confirmamos el diseño antes de grabar."/><InfoBox title="Producción" text="Tiempo estimado de 2 a 5 días hábiles."/></div></section>{related.length>0&&<section className="max-w-7xl mx-auto px-6 py-20"><h2 className="text-4xl font-black mb-10">También te puede gustar</h2><div className="grid md:grid-cols-3 gap-8">{related.map(item=><ProductCard key={item.slug} product={item}/>)}</div></section>}<Footer/><WhatsAppFloat/></main>}
